function val = MolCaMPerMolPP2B(KD5, totalCaM)
%MOLCAMPERMOLPP2B Summary of this function goes here
%   Detailed explanation goes here

val = (-(totalCaM.*(KD5 - totalPP2B + totalCaM - (KD5.^2 ...
    + 2*KD5.*totalPP2B + 2*KD5.*totalCaM + totalPP2B^2 ...
    - 2*totalPP2B.*totalCaM + totalCaM.^2).^(1/2)))./(totalPP2B.*(KD5 ...
    + totalPP2B - totalCaM + (KD5.^2 + 2*KD5.*totalPP2B + 2*KD5.*totalCaM ...
    + totalPP2B^2 - 2*totalPP2B*totalCaM + totalCaM.^2).^(1/2))));
end

